export const PRODUCT_DATA_SUCCESS = "PRODUCT_DATA_SUCCESS";
export const PRODUCT_DATA_LOADING = "PRODUCT_DATA_LOADING";
export const PRODUCT_DATA_ERROR = " PRODUCT_DATA_ERROR";


export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAILURE = "POST_FAILURE";

export const PATCH_SUCCESS = "PATCH_SUCCESS";
export const DELETE_SUCCESS = "DELETE_SUCCESS";

